import { ProfileDetails } from "@/types/details";

export const profileDetails: ProfileDetails = {
  name: "Sherwin Romero",
  description: "A front-end web developer",
  contactInfo: {
    email: "it.sherwinromero@gmail.com",
  },
  techStacks: [
    {
      category: "Primary tech stack",
      techs: [
        { name: "React.js" },
        { name: "Next.js" },
        { name: "TypeScript" },
        { name: "TailwindCSS" },
        { name: "shadcn/ui" },
      ],
    },
    {
      category: "Have experienced with",
      techs: [
        { name: "Golang" },
        { name: "Java" },
        { name: "PostgreSQL" },
        { name: "Amazon DynamoDB" },
        { name: "Redux" },
        { name: "Zustand" },
        { name: "flowbite-react/ui" },
        { name: "Bootstrap" },
        { name: "Sass" },
      ],
    },
    {
      category: "Tools",
      techs: [{ name: "Git" }, { name: "RESTful APIs" }, { name: "SourceTree" }, { name: "Jira" }],
    },
  ],
  projects: [
    {
      name: "PH Live Music",
      origin: "PH Live Music LTD",
      website: "https://phlivemusic.com/",
      description: "PH Live Music is an event booking platform. Filipino Owned, but we want it to be Globally Heard.",
      contribution:
        "Implemented UI designs for a client-facing website showcasing live events, venues, and artists, while contributing to the development and enhancement of the admin dashboard to support content and event management workflows.",
      techsUsed: [
        { name: "Next.js" },
        { name: "TypeScript" },
        { name: "TailwindCSS" },
        { name: "Zustand" },
        { name: "shadcn/ui" },
        { name: "flowbite-react/ui" },
      ],
      assets: [
        "/projects/phlivemusic/homepage.gif",
        "/projects/phlivemusic/events.gif",
        "/projects/phlivemusic/artists.gif",
        "/projects/phlivemusic/venues.gif",
        "/projects/phlivemusic/artist-profile.png",
        "/projects/phlivemusic/artist-full-profile.png",
        "/projects/phlivemusic/dashboard-events-table.png",
        "/projects/phlivemusic/dashboard-add-event.gif",
        "/projects/phlivemusic/dasboard-login.png",
      ],
    },
    {
      name: "SaaSConsole",
      origin: "Hooli Software Inc",
      website: "https://app.saasconsole.com/",
      description:
        "A fast and easy SaaS management platform designed to efficiently manage groups of users. Developed to simplify user administration and streamline SaaS operations",
      contribution:
        "Integrated key SaaS applications—Google Cloud, Slack, Asana, Hootsuite, and Bitbucket—into a SaaS management platform, enabling efficient user group management.",
      techsUsed: [
        { name: "React.js" },
        { name: "TypeScript" },
        { name: "Golang" },
        { name: "Redux" },
        { name: "Bootstrap" },
        { name: "Sass" },
        { name: "Amazon DynamoDB" },
      ],
      assets: [
        "/projects/saasconsole/saas-acts.png",
        "/projects/saasconsole/saas-dashboard.png",
        "/projects/saasconsole/saas-depts.png",
        "/projects/saasconsole/saas-groups.png",
        "/projects/saasconsole/saas-integs.png",
        "/projects/saasconsole/saas-people.png",
        "/projects/phlivemusic/saas-rbac.png",
      ],
    },
    {
      name: "MCIS ELearning",
      origin: "Three Enix Consulting Sdn Bhd",
      website: "https://lms-uat.mcis.my/dmz/",
      description:
        "MCIS eLearning system is to facilitate the management, delivery, and tracking of training programs including attendance and Training room booking. It serves as a centralized hub for organizing and administering learning materials, training programs, assessments, and communication.",
      contribution:
        "Integrated key SaaS applications—Google Cloud, Slack, Asana, Hootsuite, and Bitbucket—into a SaaS management platform, enabling efficient user group management.",
      techsUsed: [
        { name: "HTML/CSS" },
        { name: "JavaScript" },
        { name: "Sass" },
        { name: "Java" },
        { name: "Apache Velocity" },
        { name: "MSSQL" },
      ],
      assets: [
        "/projects/mcis-elearning/login.jpg",
        "/projects/mcis-elearning/edit-profile.jpg",
        "/projects/mcis-elearning/attendance.jpg",
        "/projects/mcis-elearning/catalog.jpg",
        "/projects/mcis-elearning/course-summary.jpg",
        "/projects/mcis-elearning/lectures-management.jpg",
      ],
    },
    {
      name: "PERN Workouts",
      type: "Personal Project",
      website: "https://pern-workouts.vercel.app/",
      repository: "https://github.com/2oofine/pern-workouts",
      description: "A simple application built with the PERN stack that helps users keep track of their workout todos.",
      contribution: "Developed key features including task management and user authentication.",
      techsUsed: [
        { name: "PostgreSQL" },
        { name: "Express.js" },
        { name: "React.js" },
        { name: "Node.js" },
        { name: "TypeScript" },
        { name: "Supabase" },
        { name: "JWT Auth" },
        { name: "Vercel" },
      ],
      assets: ["/projects/pern-workouts/login.jpg", "/projects/pern-workouts/task-management.jpg"],
    },
    {
      name: "EASI - Easy Access Smart Inventory",
      type: "Personal Project",
      origin: "Don Honorio Ventura State University",
      downloadLink: "https://drive.google.com/file/d/1sKXobrqjJB965Lkc1xrr-_aROrY8i4Nv/view",
      repository: "https://github.com/2oofine/easi_app",
      description:
        "An inventory management and POS system with features like notifications, Google SSO, forecasting, barcode scanning, and report generation.",
      contribution:
        "Led development of core features, including user authentication, inventory tracking, POS functionality, and reporting.",
      techsUsed: [{ name: "Flutter" }, { name: "Dart" }, { name: "Firebase" }],
      assets: [
        "/projects/easi/login.jpg",
        "/projects/easi/register.jpg",
        "/projects/easi/reset-password.jpg",
        "/projects/easi/side-menu.jpg",
        "/projects/easi/products.jpg",
        "/projects/easi/purchase-item.jpg",
        "/projects/easi/products-status.jpg",
        "/projects/easi/stats.jpg",
        "/projects/easi/forecast.jpg",
        "/projects/easi/generate-report.jpg",
      ],
    },
  ],
  socials: [
    {
      name: "LinkedIn",
      url: "https://linkedin.com/in/sherwin-romero",
    },
    {
      name: "Github",
      url: "https://github.com/2oofine",
    },
  ],
  workExps: [
    {
      company: "PH Live Music LTD",
      location: "Angeles, Pampanga",
      workSetup: "Remote",
      position: "Junior Frontend Engineer",
      techsUsed: [
        { name: "Next.js" },
        { name: "TypeScript" },
        { name: "TailwindCSS" },
        { name: "Zustand" },
        { name: "shadcn/ui" },
        { name: "flowbite-react/ui" },
      ],
      startDate: new Date("03-17-2025"),
      endDate: "Present",
    },
    {
      company: "Three Enix Consulting Sdn Bhd",
      location: "Kuala Lumpur, Malaysia",
      workSetup: "Remote",
      position: "Software Engineer",
      techsUsed: [
        { name: "HTML/CSS" },
        { name: "JavaScript" },
        { name: "Sass" },
        { name: "Java" },
        { name: "Apache Velocity" },
        { name: "MSSQL" },
      ],
      startDate: new Date("05-06-2024"),
      endDate: new Date("01-24-2025"),
    },
    {
      company: "Hooli Software Inc",
      location: "Marilao, Bulacan",
      workSetup: "Remote",
      position: "Software Engineer",
      techsUsed: [
        { name: "React.js" },
        { name: "TypeScript" },
        { name: "Golang" },
        { name: "Redux" },
        { name: "Bootstrap" },
        { name: "Sass" },
        { name: "Amazon DynamoDB" },
      ],
      startDate: new Date("06-22-2022"),
      endDate: new Date("02-29-2024"),
    },
    {
      company: "Hooli Software Inc",
      location: "Marilao, Bulacan",
      workSetup: "Remote",
      position: "Software Engineer Intern",
      techsUsed: [
        { name: "React.js" },
        { name: "TypeScript" },
        { name: "Golang" },
        { name: "Redux" },
        { name: "Bootstrap" },
        { name: "Sass" },
        { name: "Amazon DynamoDB" },
      ],
      startDate: new Date("03-28-2022"),
      endDate: new Date("06-22-2022"),
    },
  ],
};
