import { ProfileDetails } from "@/types/details";
import {
  FaAws,
  FaBootstrap,
  FaGitAlt,
  FaGithub,
  FaGolang,
  FaJava,
  FaJira,
  FaLinkedin,
  FaReact,
  FaSass,
  FaSourcetree,
} from "react-icons/fa6";
import { GiBearFace, GiFlowerTwirl } from "react-icons/gi";
import { SiNextdotjs, SiPostgresql, SiPostman, SiRedux, SiShadcnui, SiTailwindcss, SiTypescript } from "react-icons/si";
import { TbApi } from "react-icons/tb";

export const profileDetails: ProfileDetails = {
  name: "Sherwin Romero",
  profession: "Full-Stack Web Developer specializing in frontend technologies",
  contactInfo: {
    email: "it.sherwinromero@gmail.com",
  },
  techStacks: [
    {
      category: "Primary tech stack",
      techs: [
        { name: "React.js", icon: FaReact, baseColor: "text-blue-500", hoverColor: "group-hover:text-blue-500" },
        { name: "Next.js", icon: SiNextdotjs, baseColor: "text-black" },
        { name: "TypeScript", icon: SiTypescript, baseColor: "text-blue-500", hoverColor: "group-hover:text-blue-500" },
        {
          name: "TailwindCSS",
          icon: SiTailwindcss,
          baseColor: "text-blue-500",
          hoverColor: "group-hover:text-blue-500",
        },
        { name: "shadcn/ui", icon: SiShadcnui, baseColor: "text-black" },
      ],
    },
    {
      category: "Have experienced with",
      techs: [
        { name: "Golang", icon: FaGolang, baseColor: "text-blue-500", hoverColor: "group-hover:text-blue-500" },
        { name: "Java", icon: FaJava, baseColor: "text-orange-500", hoverColor: "group-hover:text-orange-500" },
        { name: "PostgreSQL", icon: SiPostgresql, baseColor: "text-blue-500", hoverColor: "group-hover:text-blue-500" },
        {
          name: "Amazon DynamoDB",
          icon: FaAws,
          baseColor: "text-orange-500",
          hoverColor: "group-hover:text-orange-500",
        },
        { name: "Redux", icon: SiRedux, baseColor: "text-violet-500", hoverColor: "group-hover:text-violet-500" },
        { name: "Zustand", icon: GiBearFace, baseColor: "text-amber-900", hoverColor: "group-hover:text-amber-950" },
        {
          name: "flowbite-react/ui",
          icon: GiFlowerTwirl,
          baseColor: "text-blue-500",
          hoverColor: "group-hover:text-blue-500",
        },
        {
          name: "Bootstrap",
          icon: FaBootstrap,
          baseColor: "text-violet-500",
          hoverColor: "group-hover:text-violet-500",
        },
        { name: "Sass", icon: FaSass, baseColor: "text-pink-500", hoverColor: "group-hover:text-pink-500" },
      ],
    },
    {
      category: "Tools",
      techs: [
        { name: "Git", icon: FaGitAlt, baseColor: "text-orange-500", hoverColor: "group-hover:text-orange-500" },
        { name: "RESTful APIs", icon: TbApi, baseColor: "text-blue-500", hoverColor: "group-hover:text-blue-500" },
        { name: "SourceTree", icon: FaSourcetree, baseColor: "text-blue-500", hoverColor: "group-hover:text-blue-500" },
        { name: "Postman", icon: SiPostman, baseColor: "text-orange-500", hoverColor: "group-hover:text-orange-500" },
        { name: "Jira", icon: FaJira, baseColor: "text-blue-500", hoverColor: "group-hover:text-blue-500" },
      ],
    },
  ],

  projects: [
    {
      name: "PH Live Music",
      origin: "PH Live Music LTD",
      website: "https://phlivemusic.com/",
      type: "worked_with",
      description: "PH Live Music is an event booking platform. Filipino Owned, but we want it to be Globally Heard.",
      contribution:
        "Implemented UI designs for a client-facing website showcasing live events, venues, and artists, while contributing to the development and enhancement of the admin dashboard to support content and event management workflows.",
      techsUsed: [
        { name: "Next.js" },
        { name: "TypeScript" },
        { name: "TailwindCSS" },
        { name: "Zustand" },
        { name: "shadcn/ui" },
        { name: "flowbite-react/ui" },
      ],
      assets: [
        "/projects/phlivemusic/homepage.gif",
        "/projects/phlivemusic/events.gif",
        "/projects/phlivemusic/artists.gif",
        "/projects/phlivemusic/venues.gif",
        "/projects/phlivemusic/artist-profile.png",
        "/projects/phlivemusic/artist-full-profile.png",
        "/projects/phlivemusic/dashboard-events-table.png",
        "/projects/phlivemusic/dashboard-add-event.gif",
        "/projects/phlivemusic/dashboard-login.png",
      ],
    },
    {
      name: "Host Quest LLC",
      origin: "Host Quest LLC",
      repository: "https://github.com/2oofine/host-quest-llc",
      type: "personal",
      description:
        "Host Quest LLC connects skilled professionals with businesses, simplifying hiring and helping both find the perfect match.",
      contribution:
        "Designed and developed the company website, focusing on an intuitive user experience and digital strategy.",
      techsUsed: [{ name: "Next.js" }, { name: "TypeScript" }, { name: "TailwindCSS" }, { name: "framer-motion" }],
      assets: [
        "/projects/host-quest-llc/home.gif",
        "/projects/host-quest-llc/services.gif",
        "/projects/host-quest-llc/about-us.gif",
        "/projects/host-quest-llc/job-seekers.gif",
        "/projects/host-quest-llc/employers.gif",
        "/projects/host-quest-llc/contact-us.gif",
      ],
    },
    {
      name: "SaaSConsole",
      origin: "Hooli Software Inc",
      website: "https://app.saasconsole.com/",
      type: "worked_with",
      description:
        "A fast and easy SaaS management platform designed to efficiently manage groups of users. Developed to simplify user administration and streamline SaaS operations.",
      contribution:
        "Integrated key SaaS applications—Google Cloud, Slack, Asana, Hootsuite, and Bitbucket—into a SaaS management platform, enabling efficient user group management.",
      techsUsed: [
        { name: "React.js" },
        { name: "TypeScript" },
        { name: "Golang" },
        { name: "Redux" },
        { name: "Bootstrap" },
        { name: "Sass" },
        { name: "Amazon DynamoDB" },
      ],
      assets: [
        "/projects/saasconsole/saas-acts.png",
        "/projects/saasconsole/saas-dashboard.png",
        "/projects/saasconsole/saas-depts.png",
        "/projects/saasconsole/saas-groups.png",
        "/projects/saasconsole/saas-integs.png",
        "/projects/saasconsole/saas-people.png",
        "/projects/saasconsole/saas-rbac.png",
      ],
    },
    {
      name: "MCIS ELearning",
      origin: "Three Enix Consulting Sdn Bhd",
      type: "worked_with",
      website: "https://lms-uat.mcis.my/dmz/",
      description:
        "MCIS eLearning streamlines training management, attendance tracking, and room booking in one platform.",
      contribution:
        "Integrated key SaaS applications—Google Cloud, Slack, Asana, Hootsuite, and Bitbucket—into a SaaS management platform, enabling efficient user group management.",
      techsUsed: [
        { name: "HTML/CSS" },
        { name: "JavaScript" },
        { name: "Sass" },
        { name: "Java" },
        { name: "Apache Velocity" },
        { name: "MSSQL" },
      ],
      assets: [
        "/projects/mcis-elearning/login.jpg",
        "/projects/mcis-elearning/edit-profile.jpg",
        "/projects/mcis-elearning/attendance.jpg",
        "/projects/mcis-elearning/catalog.jpg",
        "/projects/mcis-elearning/course-summary.jpg",
        "/projects/mcis-elearning/lectures-management.jpg",
      ],
    },
    {
      name: "PERN Workouts",
      type: "personal",
      website: "https://pern-workouts.vercel.app/",
      repository: "https://github.com/2oofine/pern-workouts",
      description: "A simple application built with the PERN stack that helps users keep track of their workout todos.",
      contribution: "Developed key features including task management and user authentication.",
      techsUsed: [
        { name: "PostgreSQL" },
        { name: "Express.js" },
        { name: "React.js" },
        { name: "Node.js" },
        { name: "TypeScript" },
        { name: "Supabase" },
        { name: "JWT Auth" },
        { name: "Vercel" },
      ],
      assets: ["/projects/pern-workouts/login.jpg", "/projects/pern-workouts/task-management.jpg"],
    },
    {
      name: "EASI - Easy Access Smart Inventory",
      type: "personal",
      origin: "Don Honorio Ventura State University",
      downloadLink: "https://drive.google.com/file/d/1sKXobrqjJB965Lkc1xrr-_aROrY8i4Nv/view",
      repository: "https://github.com/2oofine/easi_app",
      description:
        "An inventory management and POS system with features like notifications, Google SSO, forecasting, barcode scanning, and report generation.",
      contribution:
        "Led development of core features, including user authentication, inventory tracking, POS functionality, and reporting.",
      techsUsed: [{ name: "Flutter" }, { name: "Dart" }, { name: "Firebase" }],
      assets: [
        "/projects/easi/login.jpg",
        "/projects/easi/register.jpg",
        "/projects/easi/reset-password.jpg",
        "/projects/easi/side-menu.jpg",
        "/projects/easi/products.jpg",
        "/projects/easi/purchase-item.jpg",
        "/projects/easi/products-status.jpg",
        "/projects/easi/stats.jpg",
        "/projects/easi/forecast.jpg",
        "/projects/easi/generate-report.jpg",
      ],
    },
  ],
  socials: [
    {
      name: "LinkedIn",
      url: "https://linkedin.com/in/sherwin-romero",
      icon: FaLinkedin,
    },
    {
      name: "Github",
      url: "https://github.com/2oofine",
      icon: FaGithub,
    },
  ],
  workExps: [
    {
      company: "PH Live Music LTD",
      location: "Angeles, Pampanga",
      workSetup: "Remote",
      jobType: "Contract",
      position: "Junior Frontend Engineer",
      techsUsed: [
        { name: "Next.js" },
        { name: "TypeScript" },
        { name: "TailwindCSS" },
        { name: "Zustand" },
        { name: "shadcn/ui" },
        { name: "flowbite-react/ui" },
      ],
      startDate: new Date("2025-03-17"),
      endDate: new Date("2025-06-11"),
      companyLogo: "/companies/plm_logo.jpg",
    },
    {
      company: "Three Enix Consulting Sdn Bhd",
      location: "Kuala Lumpur, Malaysia",
      workSetup: "Remote",
      jobType: "Contract",
      position: "Software Engineer",
      techsUsed: [
        { name: "HTML/CSS" },
        { name: "JavaScript" },
        { name: "Sass" },
        { name: "Java" },
        { name: "Apache Velocity" },
        { name: "MSSQL" },
      ],
      startDate: new Date("2024-05-06"),
      endDate: new Date("2025-01-24"),
      companyLogo: "/companies/3enix_logo.jpg",
    },
    {
      company: "Hooli Software Inc",
      location: "Marilao, Bulacan",
      workSetup: "Remote",
      jobType: "Full-time",
      position: "Software Engineer",
      techsUsed: [
        { name: "React.js" },
        { name: "TypeScript" },
        { name: "Golang" },
        { name: "Redux" },
        { name: "Bootstrap" },
        { name: "Sass" },
        { name: "Amazon DynamoDB" },
      ],
      startDate: new Date("2022-06-22"),
      endDate: new Date("2024-02-29"),
      companyLogo: "/companies/hooli_logo.jpg",
    },
    {
      company: "Hooli Software Inc",
      location: "Marilao, Bulacan",
      workSetup: "Remote",
      jobType: "Internship",
      position: "Software Engineer Intern",
      techsUsed: [
        { name: "React.js" },
        { name: "TypeScript" },
        { name: "Golang" },
        { name: "Redux" },
        { name: "Bootstrap" },
        { name: "Sass" },
        { name: "Amazon DynamoDB" },
      ],
      startDate: new Date("2022-03-28"),
      endDate: new Date("2022-06-22"),
      companyLogo: "/companies/hooli_logo.jpg",
    },
  ],
};
